export enum ErrorCode {
    AUTH_ERROR = "AUTH_ERROR",
    INTERNAL_ERROR = "INTERNAL_ERROR",

    AMOUNT_NOT_VALID = "AMOUNT_NOT_VALID",
    CURRENCY_NOT_VALID = "CURRENCY_NOT_VALID",
    EMAIL_NOT_VALID = "EMAIL_NOT_VALID",
    PHONE_NOT_VALID = "PHONE_NOT_VALID",
    FIRST_NAME_NOT_VALID = "FIRST_NAME_NOT_VALID",
    LAST_NAME_NOT_VALID = "LAST_NAME_NOT_VALID",
    NEW_PASSWORD_NOT_VALID = "NEW_PASSWORD_NOT_VALID",
    PASSWORD_NOT_VALID = "PASSWORD_NOT_VALID",
    CONFIRM_NOT_VALID = "CONFIRM_NOT_VALID",
    COUNTRY_NOT_VALID = "COUNTRY_NOT_VALID",
    ADDRESS_NOT_VALID = "ADDRESS_NOT_VALID",
    CITY_NOT_VALID = "CITY_NOT_VALID",
    STATE_NOT_VALID = "STATE_NOT_VALID",
    ZIP_CODE_NOT_VALID = "ZIP_CODE_NOT_VALID",
    DESCRIPTION_NOT_VALID = "DESCRIPTION_NOT_VALID",
    VERIFICATION_CODE_NOT_VALID = "VERIFICATION_CODE_NOT_VALID",
    COUNT_NOT_VALID = "COUNT_NOT_VALID",
    PAGE_NOT_VALID = "PAGE_NOT_VALID",
    USERNAME_NOT_VALID = "USERNAME_NOT_VALID",
    TYPE_NOT_VALID = "TYPE_NOT_VALID",
    LINK_NOT_VALID = "LINK_NOT_VALID",
    IDENTIFICATION_TYPE_NOT_VALID = "IDENTIFICATION_TYPE_NOT_VALID",

    EMAIL_NOT_UNIQUE = "EMAIL_NOT_UNIQUE",

    PASSWORD_MISMATCH = "PASSWORD_MISMATCH",
    WRONG_EMAIL_OR_PASS = "WRONG_EMAIL_OR_PASS",

    TOO_EARLY = "TOO_EARLY",
    USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",
    NOT_FOUND = "NOT_FOUND",
    EXPIRED = "EXPIRED",
    WRONG_TOKEN = "WRONG_TOKEN",
    WRONG_PASSWORD = "WRONG_PASSWORD",
    REQUIRED_2FA = "REQUIRED_2FA",

    KYC_IN_PROGRESS = "KYC_IN_PROGRESS",
    KYC_ALREADY_DONE = "KYC_ALREADY_DONE",
    UNSUPPORTED_COUNTRY = "UNSUPPORTED_COUNTRY"
}
