export const LOGOUT_SEND = 'LOGOUT_SEND';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const FETCH_CONTENT_SEND = 'FETCH_CONTENT_SEND';
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS';
export const FETCH_CONTENT_FAILED = 'FETCH_CONTENT_FAILED';

export const FETCH_FILES_SEND = 'FETCH_FILES_SEND';
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS';
export const FETCH_FILES_FAILED = 'FETCH_FILES_FAILED';

export const CHANGE_LOG_LEVEL_FILTER = 'CHANGE_LOG_LEVEL_FILTER';
export const CHANGE_REQ_ID_FILTER = 'CHANGE_REQ_ID_FILTER';
export const CHANGE_TEXT_FILTER = 'CHANGE_TEXT_FILTER';

export const CHANGE_LINK_EMAIL = 'CHANGE_LINK_EMAIL';
export const CHANGE_LINK_TITLE = 'CHANGE_LINK_TITLE';
export const CHANGE_LINK_NAME = 'CHANGE_LINK_NAME';
export const CHANGE_LINK_CONTACT_PHONE = 'CHANGE_LINK_CONTACT_PHONE';
export const CHANGE_LINK_CONTACT_MAIL = 'CHANGE_LINK_CONTACT_MAIL';
export const CHANGE_LINK_CONTACT_NAME = 'CHANGE_LINK_CONTACT_NAME';

export const CREATE_LINK_SEND = 'CREATE_LINK_SEND';
export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS';
export const CREATE_LINK_FAILED = 'CREATE_LINK_FAILED';

export const SEND_SEND = 'SEND_SEND';
export const SEND_FAILED = 'SEND_FAILED';
export const SEND_SUCCESS = 'SEND_SUCCESS';
